<?xml version="1.0"?>
<!DOCTYPE ArrayOfProdukt
[
<!ELEMENT ArrayOfProdukt (Produkt*)>
<!ELEMENT Produkt (ProduktId,NazwaProduktu,Kalorie,Bialko,Tluszcze,Weglowodany)>
<!ELEMENT ProduktId (#PCDATA)>
<!ELEMENT NazwaProduktu (#PCDATA)>
<!ELEMENT Kalorie (#PCDATA)>
<!ELEMENT Bialko (#PCDATA)>
<!ELEMENT Tluszcze (#PCDATA)>
<!ELEMENT Weglowodany (#PCDATA)>

<!ATTLIST ArrayOfProdukt xmlns:xsi CDATA #IMPLIED>
<!ATTLIST ArrayOfProdukt xmlns:xsd CDATA #IMPLIED>
]>

<ArrayOfProdukt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Produkt>
    <ProduktId>1</ProduktId>
    <NazwaProduktu>Banan</NazwaProduktu>
    <Kalorie>100</Kalorie>
    <Bialko>1</Bialko>
    <Tluszcze>0</Tluszcze>
    <Weglowodany>24</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>2</ProduktId>
    <NazwaProduktu>Ziemniak</NazwaProduktu>
    <Kalorie>70</Kalorie>
    <Bialko>1</Bialko>
    <Tluszcze>1</Tluszcze>
    <Weglowodany>21</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>3</ProduktId>
    <NazwaProduktu>Bakłażan</NazwaProduktu>
    <Kalorie>100</Kalorie>
    <Bialko>1</Bialko>
    <Tluszcze>0</Tluszcze>
    <Weglowodany>24</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>4</ProduktId>
    <NazwaProduktu>k</NazwaProduktu>
    <Kalorie>111</Kalorie>
    <Bialko>1.1</Bialko>
    <Tluszcze>15.5</Tluszcze>
    <Weglowodany>1</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>5</ProduktId>
    <NazwaProduktu>Arbuz</NazwaProduktu>
    <Kalorie>30</Kalorie>
    <Bialko>0.6</Bialko>
    <Tluszcze>0.2</Tluszcze>
    <Weglowodany>8</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>6</ProduktId>
    <NazwaProduktu>Hamburger</NazwaProduktu>
    <Kalorie>900</Kalorie>
    <Bialko>100</Bialko>
    <Tluszcze>100</Tluszcze>
    <Weglowodany>100</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>7</ProduktId>
    <NazwaProduktu>DDDDDDDDDDDDDDD</NazwaProduktu>
    <Kalorie>900</Kalorie>
    <Bialko>100</Bialko>
    <Tluszcze>100</Tluszcze>
    <Weglowodany>100</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>8</ProduktId>
    <NazwaProduktu>Pomelo</NazwaProduktu>
    <Kalorie>38</Kalorie>
    <Bialko>0.8</Bialko>
    <Tluszcze>0</Tluszcze>
    <Weglowodany>10</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>9</ProduktId>
    <NazwaProduktu>Bułka</NazwaProduktu>
    <Kalorie>310</Kalorie>
    <Bialko>11</Bialko>
    <Tluszcze>6</Tluszcze>
    <Weglowodany>52</Weglowodany>
  </Produkt>
  <Produkt>
    <ProduktId>10</ProduktId>
    <NazwaProduktu>Cebula</NazwaProduktu>
    <Kalorie>39</Kalorie>
    <Bialko>1.1</Bialko>
    <Tluszcze>0.1</Tluszcze>
    <Weglowodany>9</Weglowodany>
  </Produkt>
</ArrayOfProdukt>